#!/usr/bin/env python3
"""
Setup script untuk Nautica Telegram Bot
Membantu konfigurasi awal bot dengan mudah
"""

import os
import sys


def print_banner():
    print("""
╔══════════════════════════════════════════╗
║                                          ║
║      🤖 JHOPAN VPN TELEGRAM BOT 🤖       ║
║                                          ║
║         Setup & Configuration            ║
║                                          ║
╚══════════════════════════════════════════╝
""")


def check_python_version():
    """Check if Python version is >= 3.8"""
    if sys.version_info < (3, 8):
        print("❌ Error: Python 3.8 or higher is required!")
        print(f"   Current version: {sys.version}")
        sys.exit(1)
    print(f"✅ Python version: {sys.version.split()[0]}")


def install_dependencies():
    """Install required packages"""
    print("\n📦 Installing dependencies...")
    os.system(f"{sys.executable} -m pip install -r requirements.txt")
    print("✅ Dependencies installed!")


def create_env_file():
    """Create .env file from user input"""
    print("\n⚙️  Configuration Setup")
    print("=" * 50)
    
    # Get bot token
    print("\n1️⃣  Telegram Bot Token")
    print("   Dapatkan dari: @BotFather di Telegram")
    print("   Command: /newbot")
    bot_token = input("\n   Enter Bot Token: ").strip()
    
    if not bot_token:
        print("   ⚠️  Skipped - You can set it later in .env file")
        bot_token = "YOUR_BOT_TOKEN_HERE"
    
    # Get worker domain
    print("\n2️⃣  Cloudflare Workers Domain")
    print("   Contoh: jhopan.workers.dev")
    print("   Atau custom domain: jhopan.yourdomain.com")
    worker_domain = input("\n   Enter Worker Domain: ").strip()
    
    if not worker_domain:
        print("   ⚠️  Using default: jhopan.workers.dev")
        worker_domain = "jhopan.workers.dev"
    
    # Get default settings
    print("\n3️⃣  Default Settings (Optional, tekan Enter untuk skip)")
    
    print("\n   Available Countries: ID, SG, US, JP, KR, DE, GB, FR")
    default_country = input("   Default Country [ID]: ").strip() or "ID"
    
    print("\n   Available Protocols: vless, trojan, ss")
    default_protocol = input("   Default Protocol [vless]: ").strip() or "vless"
    
    print("\n   Available Ports: 443, 80")
    default_port = input("   Default Port [443]: ").strip() or "443"
    
    print("\n   Available Formats: raw, clash, sfa, v2ray")
    default_format = input("   Default Format [raw]: ").strip() or "raw"
    
    default_limit = input("   Default Limit [10]: ").strip() or "10"
    
    # Write to .env file
    env_content = f"""# Jhopan Bot Configuration
# Auto-generated by setup.py

# Telegram Bot Token
TELEGRAM_BOT_TOKEN={bot_token}

# Cloudflare Workers Domain
WORKER_DOMAIN={worker_domain}

# Default Settings
DEFAULT_COUNTRY={default_country}
DEFAULT_PROTOCOL={default_protocol}
DEFAULT_PORT={default_port}
DEFAULT_FORMAT={default_format}
DEFAULT_LIMIT={default_limit}

# Logging
LOG_LEVEL=INFO

# API Settings
API_TIMEOUT=30
MAX_RETRIES=3
CACHE_DURATION=300
"""
    
    with open(".env", "w") as f:
        f.write(env_content)
    
    print("\n✅ Configuration saved to .env file!")


def update_bot_file():
    """Update telegram-bot.py with .env values"""
    print("\n📝 Updating bot configuration...")
    
    # Read .env file
    config = {}
    try:
        with open(".env", "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    config[key.strip()] = value.strip()
    except FileNotFoundError:
        print("   ⚠️  .env file not found, skipping...")
        return
    
    # Read bot file
    try:
        with open("telegram-bot.py", "r") as f:
            bot_content = f.read()
        
        # Replace values
        if "TELEGRAM_BOT_TOKEN" in config:
            bot_content = bot_content.replace(
                'TELEGRAM_BOT_TOKEN = "YOUR_BOT_TOKEN_HERE"',
                f'TELEGRAM_BOT_TOKEN = "{config["TELEGRAM_BOT_TOKEN"]}"'
            )
        
        if "WORKER_DOMAIN" in config:
            bot_content = bot_content.replace(
                'WORKER_DOMAIN = "jhopan.workers.dev"',
                f'WORKER_DOMAIN = "{config["WORKER_DOMAIN"]}"'
            )
        
        # Write back
        with open("telegram-bot.py", "w") as f:
            f.write(bot_content)
        
        print("✅ Bot file updated!")
    except Exception as e:
        print(f"   ⚠️  Error updating bot file: {e}")


def show_next_steps():
    """Show next steps to user"""
    print("\n" + "=" * 50)
    print("✨ Setup Complete!")
    print("=" * 50)
    
    print("""
📋 Next Steps:

1️⃣  Verify Configuration:
   • Check .env file
   • Make sure bot token is correct
   • Make sure worker domain is accessible

2️⃣  Test Worker Domain:
   Open in browser:
   https://YOUR_WORKER_DOMAIN/api/v1/sub?limit=1

3️⃣  Run Bot:
   python telegram-bot.py

4️⃣  Test Bot:
   • Open Telegram
   • Search for your bot username
   • Send /start command

📚 Documentation:
   • BOT_README.md - Complete guide
   • ANALISIS_PROJECT.md - Project analysis

🆘 Need Help?
   • Telegram: @foolvpn
   • GitHub Issues

🚀 Enjoy your free VPN bot!
""")


def main():
    """Main setup function"""
    print_banner()
    
    # Check Python version
    check_python_version()
    
    # Ask user what to do
    print("\n🔧 Setup Options:")
    print("1. Full Setup (Install dependencies + Configure)")
    print("2. Install Dependencies Only")
    print("3. Configure Only")
    print("4. Exit")
    
    choice = input("\nSelect option [1]: ").strip() or "1"
    
    if choice == "1":
        install_dependencies()
        create_env_file()
        update_bot_file()
        show_next_steps()
    elif choice == "2":
        install_dependencies()
        print("\n✅ Dependencies installed!")
        print("\nRun setup again with option 3 to configure.")
    elif choice == "3":
        create_env_file()
        update_bot_file()
        show_next_steps()
    elif choice == "4":
        print("\n👋 Goodbye!")
        sys.exit(0)
    else:
        print("\n❌ Invalid option!")
        sys.exit(1)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Setup cancelled by user")
        sys.exit(0)
    except Exception as e:
        print(f"\n❌ Error: {e}")
        sys.exit(1)
